### ISSUE TITLE
Non-specific error messages are frustrating and useless to the user

### ISSUE THREAD

**Issue by nikosdion** [joomla-framework/archive#14]
### Steps to reproduce the issue

* Install a component, e.g. com_foobar
* Make its directory (administrator/components/com_foobar) read-only
* Try to install an update, or the same version even, from a ZIP file

### Expected result

Something along the lines of `Cannot write to file /home/example/public_html/administrator/components/com_foobar/foobar.php`

### Actual result

The useless, if not misleading, error message `Unable to write entry`

### System information (as much as possible)

Irrelevant.

### Additional comments

The Joomla! extensions installer simply dumps the message from the RuntimeException you are throwing in the Zip and Tar classes. For example, in the ZIP class you have this code (one of two areas in the class that need to be changed):

```php
				// Make sure the destination folder exists
				if (!Folder::create(dirname($path)))
				{
					throw new \RuntimeException('Unable to create destination');
				}

				if (!File::write($path, $buffer))
				{
					throw new \RuntimeException('Unable to write entry');
				}
```

These are useless error messages. It'd be better if you did:

```php
				// Make sure the destination folder exists
				if (!Folder::create(dirname($path)))
				{
					throw new \RuntimeException('Unable to create destination folder ' . dirname($path));
				}

				if (!File::write($path, $buffer))
				{
					throw new \RuntimeException('Unable to write to file ' . $path);
				}
```

It doesn't matter if you are a developer using this class in your own code or an end user. These messages are thrown when there is a filesystem access issue. If you don't know *where* in the filesystem the issue is you cannot fix it. Moreover, "write entry" means exactly nothing, zero, nada, zilch to someone who ends up seeing this error message. Even worse, there is no indication it's a filesystem issue. The first thing that springs to mind is "database error".

This issue will be referenced in my documentation as Yet Another Joomla! Bug which prevents my clients from installing my extensions while making it impossible for me to support them. I can't help them if there is no indication of whether the problem is Joomla! extracting the extensions from the package ZIP or extracting an extension ZIP to the temporary folder or something else. No useful feedback from Joomla! = bug. Please fix it. I've provided the solution for your convenience.

**Comment by mbabker** [comment]
Fixed.

When merged to the CMS, someone will probably groan about information disclosure in the Exception messages.  My response to them will be to implement proper error handling, catch the Exceptions, and sanitize the error message shown to users as required while logging the real error data.

**Comment by nikosdion** [comment]
Thank you for the merge! And I agree; if anyone bitches about the exception tell them to do exception handling and logging. Meanwhile, in the context of extensions installation, the Super User (minimum user group to have extension installation privileges) should very damn well be able to see full paths in those error messages - something they do anyway everywhere else Joomla! provides paths. I know you know, I am just noting this down for the people who will pretend that you and I don't know what we're doing ;)
