### ISSUE TITLE
Extracting an archive using streams fails.

### ISSUE THREAD

**Issue by Achal-Aggarwal** [joomla-framework/archive#6]
First of all checkout https://bugs.php.net/bug.php?id=63195&edit=1
Now if you extract an bzip2 archive with use_stream option enabled then it doesn't extract file. It throws an exception.
On further checking I found out that on second iteration of reading (do-while loop) in Stream::read it got empty string and that caused exception.

Same is the case with gzip archive extraction using streams.

**Comment by HLeithner** [comment]
Since this seems like an PHP error and PHP closed the issue this year there is not much we can do or do you still have the problem with a current PHP version? I'm closing this for now please reopen if it still fails.
